# https://hub.docker.com/
FROM cwaffles/openpose

#get deps
RUN apt-get update

RUN pip3 install --upgrade pip

#for python api
RUN pip3 install h5py opencv-contrib-python-headless matplotlib

WORKDIR /home/experiment
RUN git clone https://github.com/mhruz/ChaLearn-SLR.git .

#ENTRYPOINT ["ls"]
CMD ./docker/run_data_prep.sh
