# https://hub.docker.com/
FROM chainer/chainer

#get deps
RUN apt-get update && \
DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git

RUN pip3 install --upgrade pip

#for python api
RUN pip3 install h5py opencv-contrib-python-headless chainercv2 pandas matplotlib

WORKDIR /home/experiment

RUN git clone https://github.com/mhruz/ChaLearn-SLR.git .

CMD ./docker/run_transformer_pred.sh



