# https://hub.docker.com/
FROM nvcr.io/nvidia/pytorch:21.02-py3

#get deps
RUN apt-get update 

RUN pip3 install --upgrade pip

#for python api
RUN pip3 install h5py albumentations opencv-contrib-python-headless

WORKDIR /home/experiment/
RUN git clone https://github.com/mhruz/ChaLearn-SLR.git .

CMD ./docker/run_vle_predict_test.sh